coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

# Ensure files that are not relevant to coverage metrics don't skew results
ignore:
  - "**/test_snapshots/**"
  - "**/target/**"
  - "**/.github/**"
  - "**/scripts/**"
